<a href="https://colab.research.google.com/github/2303A51961/23CSBTB27-28/blob/main/Array1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Part 1 – Implement Basic Data Structures using Numpy, Pandas

In [3]:
import numpy as np
List={1,5,2,6,7}
List1=[3,6,1,8]
print(List)
print(List1)
print(type(List))
print(type(List1))



{1, 2, 5, 6, 7}
[3, 6, 1, 8]
<class 'set'>
<class 'list'>


In [4]:
List1=["Geeks","For","Geeks"]
List2="my first lab"
List3=4.3
List4=2j+6
List5='my first lab'
print(type(List2))
print(type(List3))
print(type(List4))
print(type(List5))
print("\nList Items:  ")
print(List1)
print(type(List1))
print(List1[0])
print(List1[2])


<class 'str'>
<class 'float'>
<class 'complex'>
<class 'str'>

List Items:  
['Geeks', 'For', 'Geeks']
<class 'list'>
Geeks
Geeks


In [6]:
import numpy as np
arry=np.array([2,5,3,7,3])
print(arry)
print(type(arry))

[2 5 3 7 3]
<class 'numpy.ndarray'>


In [5]:
List = {1:"greek1",2:'Geeks', 'For':3,'Geeks':6}
print("\nList with the use of Mixed Values: ")
print(List)
print(type(List))


List with the use of Mixed Values: 
{1: 'greek1', 2: 'Geeks', 'For': 3, 'Geeks': 6}
<class 'dict'>


In [9]:
import numpy as np
arry=np.array([[2,5],[4,2]])
arry1=np.array([[2,5,4,2],[4,2,1,0]])
arry2=np.array([[2,5,4],[4,2,5],[6,7,8]])
print(arry)
print(arry1)
print(arry2)

[[2 5]
 [4 2]]
[[2 5 4 2]
 [4 2 1 0]]
[[2 5 4]
 [4 2 5]
 [6 7 8]]


In [12]:
import numpy as np
arry1=np.array([1,3,4,5,6])
arry2=np.array([2,6,3,4,8])
print(arry1)
print(np.add(arry1,arry2))
print(np.multiply(arry1,arry2))
print(np.subtract(arry2,arry1))
print(np.divide(arry2,arry1))
print(type(arry1))

[1 3 4 5 6]
[ 3  9  7  9 14]
[ 2 18 12 20 48]
[ 1  3 -1 -1  2]
[2.         2.         0.75       0.8        1.33333333]
<class 'numpy.ndarray'>
